on:
  push:
    branches:
      - release*

jobs:
  release:
    environment: Release
    steps:
      - name: Parse release version
        run: |
          ref="${{ github.ref }}"
          branch=${ref/refs\/heads\//}
          version=${branch/release\//}
      - name: Create release
        run: |
          echo version: $version
          echo branch: $branch
          echo ref: $ref
